site_name: lemonjuce

nav:
  - Home: index.md
  - Getting Started:
      - What is JUCE?: getting_started/what_is_juce.md
      - Installation: getting_started/installation.md
      - Creating an audio plugin: getting_started/creating_an_audio_plugin.md
      - Plugin architecture: getting_started/plugin_architecture.md
  - Advanced:
    - Implementing an AudioProcessorValueTreeState: advanced/implementing_an_audioprocessorvaluetreestate.md

theme:
  name: readthedocs