site_name: JUCEDocs

nav:
  - Tutorials:
    - Whats JUCE and how to use it: tutorials/whats_juce_and_how_to_use_it/whats_juce_and_how_to_use_it.md
    - Getting started with the JUCE framework: tutorials/getting_started_with_the_JUCE_framework/getting_started_with_the_JUCE_framework.md
    - Simple Gain Plugin: tutorials/simple_gain_plugin/simple_gain_plugin.md
  - Modules:
    - dsp:
      - gain: modules/dsp/gain.md