site_name: lemonjuce

nav:
  - Home: index.md
  - Getting Started:
    - What is JUCE?: getting_started/what_is_juce.md
    - Installation: getting_started/installation.md
    - Creating an audio plugin: getting_started/creating_an_audio_plugin.md
    - Plugin architecture: getting_started/plugin_architecture.md
    - Setup CMake with JUCE: getting_started/setup_cmake_with_juce.md
  - GUI:
    - Creating a custom LookAndFeel: gui/creating_a_custom_lookandfeel.md
  - Parameter Handling:
    - Implementing an APVTS: parameter_handling/implementing_an_apvts.md
  - DSP:
    - Implementing a Dry Wet Mixer: dsp/implementing_a_dry_wet_mixer.md
    - Implementing an IIR Filter: dsp/implementing_an_iir_filter.md
  - Information:
    - Contributing page: information/contributing.md
    - Other resources: information/other_resources.md

theme:
  name: readthedocs
