site_name: JUCEDocs

nav:
  - Home: index.md
  - Getting Started:
      - What is JUCE?: getting_started/what_is_juce/what_is_juce.md
      - Installation: getting_started/installation/installation.md