site_name: JUCEDocs

nav:
  - Home: index.md
  - Getting Started:
      - What is JUCE?: getting_started/what_is_juce/what_is_juce.md
      - Installation: getting_started/installation/installation.md
      - Creating an audio plugin: getting_started/creating_an_audio_plugin/creating_an_audio_plugin.md
      - Plugin architecture: getting_started/plugin_architecture/plugin_architecture.md